---
title: "R Notebook"
output:
  pdf_document: default
  pdf_notebook: default
---

## Without Mixtures

We first load the ClaritySim and Clarity package and simulate some appropriate data:

```{r}
library(ClaritySim)
library(Clarity)
set.seed(1)
n=100 
k=10
original <- simulateCoalescent(n,k,
                         sigma0=0.0001,
                         Amodel="uniform",
                         alpha=0,
                         minedge=0.1) # Simlulate 100 objects in a 10 dimensional latent space

similar <- transformCoalescent(original)

```

We can now visualize the trees from these 3 different simulated data:

```{r}
par(mfrow = c(1,2))
plot(original$tree)
plot(similar$tree)
```

We now obtain the similarity matrices for the subjects in both models

```{r}
original_dist <- original$Y

similar_dist <- similar$Y
```

### Predicting the Transformed Data from the Original

```{r}
original_scan <- Clarity_Scan(original_dist)

similar_predict <- Clarity_Predict(similar_dist, original_scan)

similar_compare <- Clarity_Compare(original_scan, D = original$D, Dnew = similar$D, nbs = 200, H0="structure")
```

We can now plot aspects of the predictions:

```{r}
tdist <- dist(original_dist)

clusters <- hclust(tdist)

tend <- as.dendrogram(clusters)

order <- labels(reorder(tend, colMeans(as.matrix(tdist))))


```

## With Mixtures

```{r}
mixture <- mixCoalescent(original)

mixture_dist <- mixture$Y
```
